Repository estahn/k8s-image-swapper, pull requests merged in 2023-03, with the labels that each got.

#447 Support Google Artifact Registry as target
  cmd/root.go
  docs/configuration.md
  docs/getting-started.md
  docs/img/gcp_artifact_registry.png
  go.mod
  go.sum
  mkdocs.yml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/registry/client.go
  pkg/registry/ecr.go
  pkg/registry/gar.go
  pkg/types/types.go
  pkg/webhook/image_copier.go
  pkg/webhook/image_copier_test.go
  pkg/webhook/image_swapper.go
  pkg/webhook/image_swapper_test.go
Labels: enhancement, codeball:needs-careful-review

#394 Support for managed pulling from private ECRs
  cmd/root.go
  docs/configuration.md
  docs/faq.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/registry/client.go
  pkg/registry/ecr.go
  pkg/registry/ecr_test.go
  pkg/registry/gar.go
  pkg/secrets/dummy.go
  pkg/secrets/kubernetes.go
  pkg/secrets/kubernetes_test.go
  pkg/secrets/provider.go
  pkg/types/types.go
  pkg/webhook/image_swapper.go
  pkg/webhook/image_swapper_test.go
Labels: enhancement, codeball:needs-careful-review

#487 Move accessPolicy into ecrOptions
  docs/getting-started.md
Labels: codeball:approved, docs

#489 Ability to disable image copying (ImageCopyPolicy=none)
  .k8s-image-swapper.yml
  docs/configuration.md
  pkg/config/config.go
  pkg/types/types.go
  pkg/types/types_test.go
  pkg/webhook/image_swapper.go
Labels: enhancement

#488 fix: GAR registry domain skip logic
  pkg/registry/client.go
  pkg/registry/ecr.go
  pkg/registry/ecr_test.go
  pkg/registry/gar.go
  pkg/registry/gar_test.go
  pkg/webhook/image_swapper.go
  pkg/webhook/image_swapper_test.go
  test/requests/admissionreview-simple.json
Labels: bugfix
