Repository estahn/k8s-image-swapper, pull requests merged in 2023-01, with the labels that each got.

#429 Ensure multi-arch images are copied
  pkg/webhook/image_swapper.go
Labels: codeball:needs-careful-review

#425 :bug: fix multiple tags +error logs not send + tags documentation
  .k8s-image-swapper.yml
  cmd/root.go
  docs/configuration.md
  pkg/registry/ecr.go
  pkg/webhook/image_swapper.go
  pkg/webhook/image_swapper_test.go
Labels: codeball:needs-careful-review

#422 Fix data race issue on copyFn when there are multiple containers or initContainers
  cmd/root.go
  docs/configuration.md
  pkg/config/config.go
  pkg/registry/client.go
  pkg/registry/ecr.go
  pkg/secrets/dummy.go
  pkg/secrets/dummy_test.go
  pkg/secrets/kubernetes.go
  pkg/secrets/kubernetes_test.go
  pkg/secrets/provider.go
  pkg/webhook/image_copier.go
  pkg/webhook/image_copier_test.go
  pkg/webhook/image_swapper.go
  pkg/webhook/image_swapper_test.go
Labels: bug, codeball:needs-careful-review

#451 Update styling of documentation
  docs/getting-started.md
  mkdocs.yml
Labels: codeball:approved, docs

#458 chore: retire semantic-release in favour of release-drafter
  .github/workflows/auto-merge.yml
  .github/workflows/conventional-label.yaml
  .github/workflows/deploy.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: ignore-for-release
