Repository estahn/k8s-image-swapper, pull requests merged in 2024-02, with the labels that each got.

#669 fix: expire cache items after 24h+
  pkg/registry/ecr.go
  pkg/registry/gar.go
Labels: bug, bugfix

#599 fix: overridden typo
  docs/configuration.md
Labels: docs, bugfix

#678 fix: ability to pass imageTagMutability via config
  .github/workflows/codeql-analysis.yml
  cmd/root.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/registry/ecr.go
Labels: bugfix
